### PR TITLE
Use __DIR__ instead of relative path finding

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rikschennink** [comment]
why?

**Comment by ghost** [comment]
It's a very specific use case but generally, it's just better.

Say you have a file that requires **index.php** then the include path will always be relative to the file which requires **index.php**.

In my case I have the following code in a plugin for WordPress:

```php
add_action('rest_api_init', function () {
	register_rest_route('plugin/v1', '/upload', array(
		'methods' => WP_REST_Server::ALLMETHODS,
		'callback' => [$this, "image_upload"],
	));
});
```

```php
public function image_upload() {
	define("FILEPOND_PATH", plugin_dir_path(__FILE__) . "vendor/filepond-server-php/");
	require_once FILEPOND_PATH . "index.php";
}
```

Without the proposed changes this produces an error:

```html
<br />
<b>Warning</b>:  require_once(./Helper/Transfer.class.php): failed to open stream: No such file or directory in <b>/wordpress/web/app/plugins/plugin/public/vendor/filepond-server-php/FilePond.class.php</b> on line <b>5</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required './Helper/Transfer.class.php' (include_path='.:/usr/share/php') in <b>/wordpress/web/app/plugins/plugin/public/vendor/filepond-server-php/FilePond.class.php</b> on line <b>5</b><br />
```

**Comment by rikschennink** [comment]
Hi, That makes sense, not sure why you closed the PR?

**Comment by ghost** [comment]
Reopened https://github.com/pqina/filepond-server-php/pull/13 and it also fixes https://github.com/pqina/filepond-server-php/issues/8

**Pull request closed without merging**
